new Tabulator("#datir-table", {
    //layout: "fitColumns",
   // renderHorizontal:"virtual",
    pagination:"local",
    paginationSize:10,
    paginationSizeSelector:[5, 10, 20, 100],
    movableColumns:true,
    paginationCounter:"rows",
    maxHeight:"100%",
    


    "columns": [

        {
            "title": "Atkritumu veids", 
            "field": "a"},
        {
            "title": "Komersants, kurš pieņēma atkritumus no Savācēja", 
            "field": "b",
           // headerFilter:true
        },
        {
            "title": "Pārstrādātais/reģenerētais apjoms (t)", 
            "field": "c",
            bottomCalc:"sum"
        },
        {
            "title": "Gala pārstrādātājs/reģenerētājs", 
            "field": "d"},
        {
            "title": "Reģions", 
            "field": "e"},
        {
            "title": "Darbības tips", 
            "field": "f"},
        {
            "title": "R-kods", 
            "field": "g"},
        {
            "title": "Apsaimniekotāja līdzfinansējums (euro) par pārstrādāto/reģenerēto apjomu", 
            "field": "h",
            bottomCalc:"sum"
        },
        {
            "title": "Apsaimniekotāja līdzfinansējuma par pārstrādāto/reģenerēto apjomu saņēmējs – komersanta nosaukums", 
            "field": "i"},
        {
            "title": "Starpnieks", 
            "field": "j"},
         {
            title: "Lasīšanai",
            field: "lasisanai",
            formatter: "rowSelection",
            width: "100", 
            hozAlign: "center",
            headerSort: false,
            cellClick: function (e, cell) {
                cell.getRow().toggleSelect();
            },
            titleFormatter: function (cell, formatterParams, onRendered)
            {
                cell.getElement().style.textAlign = 'center';
                return '' + cell.getValue()
            }
        }
    ],

    "data": [
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        },
        {
            "a":"Pudeles",
            "b":"SIA Eko Māja",
            "c":"100",
            "d":"SIA Regenerators",
            "e":"Kurzeme",
            "f":"Izjaukšana",
            "g":"123",
            "h":"2000000",
            "i":"SIA Fintek",
            "j":"SIA Starpniecības ABC",
            "k":"Jā"
        }
        
    ]
});