

new Tabulator("#datir-table", {

    locale: "lv-lv",
    langs: {
        "lv-lv": {

            "ajax": {
                "loading": "Loading", //ajax loader text
                "error": "Error", //ajax error text
            },
            "groups": {//copy for the auto generated item count in group header
                "item": "item", //the singular  for item
                "items": "items", //the plural for items
            },
            "pagination": {
                "first": "Pirmā", //text for the first page button
                "first_title": "Pirmā lapa", //tooltip text for the first page button
                "last": "Pēdējā",
                "last_title": "Last Page",
                "prev": "Atpakaļ",
                "prev_title": "Iepriekšējā lapa",
                "next": "Tālāk",
                "next_title": "Nākamā lapa",
                "page_size": "Skaits lapā",
                "all": "Visas",
                "counter": {
                    "showing": "Rāda",
                    "of": "no",
                    "rows": "",
                    "pages": "lapas",
                }
            },
            "headerFilters": {
                "default": "atlasīt kolonnu...", //default header filter placeholder text

            }
        }
    },
    columnHeaderVertAlign: "bottom",
    resizableRows: true,
    pagination: "local",
    paginationSize: 10,
    paginationSizeSelector: [5, 10, 20, 100],
    movableColumns: true,
    paginationCounter: "rows",
    maxHeight: "100%",

    layout: "fitDataStretch",

    "columns": [

        {
            "title": "Atkritumu veids",
            "field": "a",
            headerFilter: "input",
            frozen: true
        },
        {
            "title": "Komersants, kurš pieņēma atkritumus no Savācēja",
            "field": "b",
            width: 300,
            headerFilter: "input",
            formatter: "link", formatterParams: {
                labelField: "b",
                urlPrefix: "#",
                target: "_blank",
            }
        },
        {
            "title": "Pārstrādātais / reģenerētais apjoms (t)",
            "field": "c",
            bottomCalc: "sum",
            width: 150,
            headerFilter: "input",
            hozAlign: "right"
        },
        {
            "title": "Gala pārstrādātājs / reģenerētājs",
            "field": "d", headerFilter: "input", width: 300
        },
        {
            "title": "Reģions",
            "field": "e", headerFilter: "input"
        },
        {
            "title": "Darbības tips",
            "field": "f", headerFilter: "input"
        },
        {
            "title": "R-kods",
            "field": "g", headerFilter: "input"
        },
        {
            "title": "Apsaimniekotāja līdzfinansējums (euro) par pārstrādāto/reģenerēto apjomu",
            "field": "h",
            headerFilter: "input",
            bottomCalc: "sum",
            width: 200
        },
        {
            "title": "Apsaimniekotāja līdzfinansējuma par pārstrādāto/reģenerēto apjomu saņēmējs – komersanta nosaukums",
            headerFilter: "input",
            "field": "i",
            width: 300
        },
        {
            "title": "Starpnieks",
            headerFilter: "input",
            "field": "j",
            width: 300
        },
        {
            title: "Lasīšanai",
            field: "lasisanai",
            formatter: "rowSelection",
            width: "100",
            hozAlign: "center",
            headerSort: false,
            cellClick: function (e, cell) {
                cell.getRow().toggleSelect();
            },
            titleFormatter: function (cell, formatterParams, onRendered)
            {
                cell.getElement().style.textAlign = 'center';
                return '' + cell.getValue()
            }
        }
    ],

    "data": [
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC Starpniecības ABC Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Zip Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        },
        {
            "a": "Pudeles",
            "b": "SIA Eko Māja",
            "c": "100",
            "d": "SIA Regenerators",
            "e": "Latvija",
            "f": "Izjaukšana",
            "g": "123",
            "h": "2000000",
            "i": "SIA Fintek",
            "j": "SIA Starpniecības ABC",
            "k": "Jā"
        }

    ]
});


$("#download-xlsx").click(function (e) {
    $("#datir-table").tabulator("download", "xlsx", "data.xlsx");
});



